@Cinestar_WebApi_HostAddress = http://localhost:5286

GET {{Cinestar_WebApi_HostAddress}}/api/Cinestar/GetCines
Accept: application/json

###

GET {{Cinestar_WebApi_HostAddress}}/api/Cinestar/GetCine/1
Accept: application/json



